name: ci

on:
  push:
    branches:
      - "master"

jobs:
  test:
    name: CI
    runs-on: mac-latest
    steps:
      - uses: actions/checkout@v3
      - name: Healthcheck
        run: ./docker_compose_wrapper.sh
